name: animey
description: A anime log.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.0.9+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: 0.12.0+1
  image_downloader: 0.11.1
  url_launcher: ^4.0.3
  cached_network_image: 0.6.2
  transparent_image: 0.1.0
  shared_preferences: 0.5.1+1
  sqflite: 1.1.0
  rxdart: 0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - database/data.db
  - assets/ic_launcher.png
  - assets/streamer_logo/amazon.png
  - assets/streamer_logo/crunchyroll.png
  - assets/streamer_logo/funimation.png
  - assets/streamer_logo/hidive.png
  - assets/streamer_logo/hulu.png
  - assets/streamer_logo/netflix.png
  - assets/streamer_logo/tubitv.png
  - assets/streamer_logo/viewster.png
  - assets/streamer_logo/youtube.png

  fonts:
  - family: Noto
    fonts:
      - asset: fonts/noto/NotoSerifSC-Regular.otf
      - asset: fonts/noto/NotoSerifSC-Medium.otf
      - asset: fonts/noto/NotoSerifSC-Light.otf
      - asset: fonts/noto/NotoSerifSC-ExtraLight.otf
      - asset: fonts/noto/NotoSerifSC-Bold.otf
      - asset: fonts/noto/NotoSerifSC-SemiBold.otf
      - asset: fonts/noto/NotoSerifSC-Black.otf
  - family: Roboto
    fonts:
      - asset: fonts/roboto/Roboto-Regular.ttf
      - asset: fonts/roboto/Roboto-Medium.ttf
      - asset: fonts/roboto/Roboto-Light.ttf
      - asset: fonts/roboto/Roboto-Thin.ttf
      - asset: fonts/roboto/Roboto-Bold.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
